language: java
jdk:
- oraclejdk8
script: "mvn clean install -P with-topmenubar -P with-applauncher"
script: "mvn cobertura:cobertura -P with-topmenubar -P with-applauncher"
after_success:
- bash <(curl -s https://codecov.io/bash)
