version: '2'
services:
  lb1:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      default_cert: '@host.defaultCert@'
      port_rules:
      - protocol: https
        selector: project=topmenubar
        source_port: 444
        target_port: 444
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate